### PR TITLE
docs: Tabs-block multi language quickstart examples

### PR DESCRIPTION
**Pull request by Sambigeara**
Extends Antora to add a switchable UI allowing users to tab between an initial selection of our SDKs in the Quickstart section (other languages will be added later)

### CODE REVIEW

**Comment by Sambigeara** [comment]
Still have Java and .NET to add, but I'm _totally_ unfamiliar with those technologies and it'll probably take me a while to get them set up/tested, so figured it might be prudent to get this out there for review. Could even add those languages in a future PR.

Maybe we could get a preview generated again?

**Comment by charithe** [comment]
I had added an automatic preview action but it [appears to be buggy](https://github.com/cerbos/cerbos/runs/7677038622?check_suite_focus=true). I will try to get a quick preview action done and tweak it later.

@oguzhand95 Can you help out with the .NET example?

**Comment by charithe** [comment]
Preview: https://62ec0bad8e24d60fc3d9273a--cerbos-docs.netlify.app/cerbos/prerelease/quickstart.html

**Review by charithe — DISMISSED** [review]
LGTM. This is really cool 👍🏽 

We can add the other languages in separate PRs.

**Comment by Sambigeara** [comment]
Oh damn, sorry @charithe, I did not realise a rebase and force push would override your review 🤦‍♂️ . Will accept the auto-merge next time!

**Review by charithe — APPROVED** [review]

**Comment by charithe** [comment]
No worries. Feel free to tweak away even after the PR is approved.

**Pull request merged**
