### PR TITLE
chore: Use admin client in decisions subcommand

### PR DESCRIPTION
**Pull request by isdevx**
Signed-off-by: serdar <serdar@cerbos.dev>

#### Description

We can use the new admin client here as well. Great opportunity to remove some code :)

#### Checklist 

- [x] The PR title has the correct prefix 
- [ ] PR is linked to the corresponding issue
- [x] All commits are signed-off (`git commit -s ...`) to provide the [DCO](https://developercertificate.org/)

### CODE REVIEW

**Review by charithe — COMMENTED** [review]
Sorry to nitpick, but, I was thinking more along the lines of an `internal` package to hold common code rather than a public one. Also, "commands" in this context is a bit misleading because it gives the impression that it is the package containing all the commands.

**Comment by charithe** [comment]
Hyrum's law kind of applies here. Even though it should be obvious that `cerbosctl` package is not a library, it will still show up in Go docs and nothing prevents someone from building something using it. Given that this is an open source project, we don't have a lot of control over what people do with it so I'd prefer to minimise the exposure area if possible.

Does the additional nesting of packages add much value other than aesthetics? I'd prefer to keep the package structure flatter.

**Comment by isdevx** [comment]
OK, with that point of view -which sounds good to me- we can choose to put every subcommand inside the `internal/commands` package and have a nice flat layout and share the common bits altogether. In fact, I used kind of a similar layout on other projects (w/o the `internal` bit).

**Comment by charithe** [comment]
Just to be clear, all I am suggesting is to rename the `commands` package to `internal`. The current package structure is otherwise fine with me.

**Review by charithe — APPROVED** [review]
LGTM

**Pull request merged**
