### PR TITLE
chore: Disable CGO for "all" make target

### PR DESCRIPTION
**Pull request by dbuduev**
Follow up to https://github.com/cerbos/cerbos/pull/1336.

Signed-off-by: Dennis Buduev <dennis@cerbos.dev>

### CODE REVIEW

**Review by charithe — COMMENTED** [review]
Why just this line and not the line above as well?

**Comment by charithe** [comment]
Yes, and the Go file it generates is only used to generate a documentation page. It doesn't get compiled into the Cerbos binary. Even though there's no harm in disabling CGO, I don't think we need to do it in this instance.

**Comment by dbuduev** [comment]
I understand that the generated utility doesn't get into the cerbos binary, but this is not clear to someone who runs `make all` and gets the deprecation warning because the generated utility imports cerbos:
```bash
$ go version -m generated | grep cerbos
	dep	github.com/cerbos/cerbos	(devel)
```

**Review by charithe — APPROVED** [review]
Ah, I see your point now.

**Pull request merged**
